//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSANPHAM
    {
        public int MaCTSP { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string DoPhanGiai { get; set; }
        public string KichThuocManHinh { get; set; }
        public string DoSangToiDa { get; set; }
        public string MatKinhCarmUng { get; set; }
        public string QuayPhim { get; set; }
        public string DenFlash { get; set; }
        public string TinhNang { get; set; }
        public string HeDieuHanh { get; set; }
        public string ChipXuLy { get; set; }
        public string TocDocCPU { get; set; }
        public string Ram { get; set; }
        public string DungLuong { get; set; }
        public string DanhBa { get; set; }
        public string MangDiDong { get; set; }
        public string Sim { get; set; }
        public string Wifi { get; set; }
        public string GPS { get; set; }
        public string Bluetooth { get; set; }
        public string CongKetNoi { get; set; }
        public string JackTaiNghe { get; set; }
        public string LoaiPin { get; set; }
        public string DungLuongPin { get; set; }
        public string HoTroSacToiDa { get; set; }
        public string CongNghePin { get; set; }
        public string BaoMatNangCao { get; set; }
        public string TinhNangDatBiet { get; set; }
        public string KhangNuocBui { get; set; }
        public string GhiAm { get; set; }
        public string XemPhim { get; set; }
        public string NgheNhac { get; set; }
        public string ThietKe { get; set; }
        public string ChatLieu { get; set; }
        public string KichThuocKhoiLuong { get; set; }
        public string ThoiDiemRaMat { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
