//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITHANHVIEN_QUYEN
    {
        public int MaLTV { get; set; }
        public string MaQuyen { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LOAITHANHVIEN LOAITHANHVIEN { get; set; }
        public virtual QUYEN QUYEN { get; set; }
    }
}
